import type { Metadata } from 'next';
import Link from 'next/link';
import { PeriodThresholds } from '@/components/learn/PeriodThresholds';
import { BreakerComparison } from '@/components/learn/BreakerComparison';
import { SpectrumViewer } from '@/components/learn/SpectrumViewer';

export const revalidate = 86400;

export const metadata: Metadata = {
  title: { absolute: 'Understanding swell period | Stormy Petrel' },
  description:
    'Learn why swell period matters more than wave height. Interactive tools show how a 3ft swell at 16 seconds breaks the same size as a 5ft swell at 8 seconds.',
  alternates: { canonical: '/learn/swell-period' },
  openGraph: {
    title: 'Understanding swell period | Stormy Petrel',
    description:
      'Why the number labeled Tp on a buoy report matters more than wave height.',
    type: 'article',
  },
};

export default function SwellPeriodArticle() {
  return (
    <article className="mx-auto max-w-[720px] px-4 sm:px-6 py-10 sm:py-14">
      <nav className="mb-4 text-xs text-text-muted">
        <Link href="/learn" className="hover:text-cyan-600">
          ← All guides
        </Link>
      </nav>

      <header className="mb-8">
        <div className="text-[11px] uppercase tracking-widest2 text-text-secondary">
          Learn · 8 min read
        </div>
        <h1 className="mt-1 text-3xl sm:text-4xl font-bold tracking-tightish text-text-primary">
          Understanding swell period
        </h1>
        <p className="mt-3 text-base sm:text-lg text-text-secondary leading-relaxed">
          The number that matters more than wave height.
        </p>
      </header>

      <div className="space-y-6 text-base sm:text-lg text-text-primary leading-relaxed">
        <p>
          Most surfers check wave height first. Period tells you more about
          what you&rsquo;ll actually find at the beach.
        </p>

        <p>
          Swell period, labeled Tp on a buoy report, is the time in seconds
          between successive wave crests passing a fixed point. It sounds
          simple, but period controls almost everything about how a wave
          behaves: how fast it travels, how much energy it carries, how it
          bends around headlands, and how big it actually breaks at your
          beach.
        </p>

        <SectionHeading>What period tells you about a swell&rsquo;s origin</SectionHeading>

        <p>Period is a fingerprint of how the swell was made.</p>

        <p>
          Wind swell is generated by local or nearby weather, usually within a
          few hundred miles of the coast. The wind hasn&rsquo;t blown long
          enough or far enough to organize the waves, so the period stays
          short (5&ndash;9 seconds) and the waves arrive choppy and
          disorganized.
        </p>

        <p>
          Groundswell is generated by intense, persistent storms thousands of
          miles away. The wind blows hard across a long stretch of open ocean
          (called fetch) for days, building waves with long periods (14
          seconds and above) that travel across the ocean as clean, organized
          lines.
        </p>

        <p>
          The reason is dispersion. Different period waves travel at different
          speeds. In deep water, wave speed is approximately 1.56 times the
          period in seconds, measured in meters per second. A 16-second swell
          travels at about 56 mph. An 8-second swell moves at half that speed.
          The long-period energy outruns the short stuff, arriving at your
          coast first as clean, organized lines. The short-period chop
          straggles in later.
        </p>

        <p>
          This is why, when a major swell is approaching, the buoy period
          jumps up before the height does. A sudden spike to 18 or 20 seconds
          with small height is the leading edge of something big. Experienced
          surfers treat this forerunner as a 12&ndash;36 hour heads-up.
        </p>

        <ComponentLabel>
          Period ranges at a glance — interactive reference
        </ComponentLabel>
        <PeriodThresholds />

        <SectionHeading>Why period affects wave power</SectionHeading>

        <p>
          A wave&rsquo;s energy at a single point depends only on its height.
          Double the height, quadruple the energy. Period doesn&rsquo;t factor
          in.
        </p>

        <p>
          But what reaches your beach isn&rsquo;t energy at a single point.
          It&rsquo;s the total power moving toward shore, which scales with
          both the size of the wave and how long the period is. In plain
          terms: doubling the period doubles the power delivered to the coast
          at any given height.
        </p>

        <p>
          This is why a 3-foot swell at 16 seconds feels so much more powerful
          than a 5-foot swell at 8 seconds, even though the shorter-period
          swell has more raw height. The long-period swell is pushing energy
          through a deeper column of water, and it&rsquo;s delivering that
          energy faster.
        </p>

        <SectionHeading>Why long-period swells break bigger</SectionHeading>

        <p>This is the part that surprises people.</p>

        <p>
          As a wave approaches shore and the water gets shallower, it
          &ldquo;feels the bottom.&rdquo; The base of the wave&rsquo;s orbital
          motion drags on the seabed, the wave slows down, and the height
          grows to conserve energy. This is called shoaling.
        </p>

        <p>
          Here&rsquo;s the key: a long-period wave starts feeling the bottom
          in much deeper water. A 16-second swell begins interacting with the
          seabed at roughly 650 feet of depth. An 8-second swell doesn&rsquo;t
          feel anything until about 160 feet. The long-period swell has a
          longer runway to pile up energy into the breaking wave.
        </p>

        <p>
          Using the Komar and Gaughan breaker height formula from their 1972
          paper, you can see exactly how much each swell amplifies from deep
          water to the breaking point.
        </p>

        <ComponentLabel>
          Breaker height calculator — adjust the sliders to compare two swells
        </ComponentLabel>
        <BreakerComparison />

        <p>
          A 3-foot swell at 16 seconds amplifies by about 1.9 times, breaking
          at roughly 5.8 feet. A 5-foot swell at 8 seconds amplifies by about
          1.3 times, breaking at roughly 6.5 feet. Two swells that look
          completely different on the buoy produce nearly the same breaking
          wave. But the long-period wave will have a steeper face, more push
          down the line, and a cleaner shape.
        </p>

        <SectionHeading>How to read period on a buoy report</SectionHeading>

        <p>
          NDBC buoys report two period values. Peak period (DPD) is the
          period of the frequency band carrying the most energy. It&rsquo;s
          the period of the dominant swell. Average period (APD) is a
          weighted mean across all frequencies.
        </p>

        <p>
          The gap between DPD and APD tells you how clean the ocean is:
        </p>

        <p>
          When DPD and APD are within a couple seconds of each other, almost
          all the energy is concentrated in one swell. Conditions will be
          organized and clean.
        </p>

        <p>
          When DPD is much higher than APD (say DPD 14 seconds, APD 7
          seconds), there&rsquo;s a long-period groundswell with a lot of
          short-period wind chop sitting on top. The sets will be there, but
          the faces will be bumpy.
        </p>

        <p>
          When DPD and APD are both low and close together (both around
          5&ndash;6 seconds), it&rsquo;s all wind swell. No groundswell in
          the water.
        </p>

        <ComponentLabel>
          Buoy energy spectrum — toggle between clean and messy conditions
        </ComponentLabel>
        <SpectrumViewer />
      </div>

      <footer className="mt-12 pt-6 border-t border-ink-600 text-sm">
        <Link href="/learn" className="text-cyan-600 hover:underline">
          ← All guides
        </Link>
      </footer>
    </article>
  );
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="pt-4 text-xl sm:text-2xl font-bold tracking-tightish text-text-primary">
      {children}
    </h2>
  );
}

function ComponentLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="pt-2 text-[11px] uppercase tracking-widest2 font-bold text-text-secondary">
      {children}
    </div>
  );
}
