-- 011: durable NDBC buoy coordinate snapshot table.
--
-- There was no `buoys` table, so a stored spots.nearest_buoy_id could not be joined to a coordinate
-- and buoy assignments could not be audited in SQL without a live NDBC fetch — we spent an hour
-- inferring buoy locations from id prefixes. This table is the committed id->lat/lng snapshot
-- (pipeline/data/ndbc_buoy_snapshot.json, generated by pipeline.snapshot_buoys), mirrored here by
-- pipeline.db_import.import_buoy_snapshot on each full-pipeline run. It also backs the import-time
-- consistency check in db_import._validate_coord_derived.
--
-- Audit example — spots whose stored buoy distance disagrees with the true great-circle distance:
--   SELECT s.slug, s.nearest_buoy_id, s.nearest_buoy_dist_km,
--          6371 * 2 * asin(sqrt( ... )) AS great_circle_km   -- (spot vs buoys.lat/lng)
--   FROM spots s JOIN buoys b ON b.id = s.nearest_buoy_id
--   WHERE abs(great_circle_km - s.nearest_buoy_dist_km) > 5;

CREATE TABLE IF NOT EXISTS buoys (
  id          text PRIMARY KEY,
  lat         double precision NOT NULL,
  lng         double precision NOT NULL,
  name        text,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE buoys IS
  'NDBC buoy coordinate snapshot; populated by pipeline.db_import.import_buoy_snapshot from '
  'pipeline/data/ndbc_buoy_snapshot.json (regenerated by pipeline.snapshot_buoys). Lets buoy '
  'assignments be validated/audited in SQL without a live NDBC fetch.';
