-- Migration 018 — widen tide_preference, and record where the value came from.
--
-- WHAT WENT WRONG. tide_preference is not a measurement. Every one of the 446 populated
-- values was generated by a language model from a prompt that instructed it to produce an
-- answer whether or not it had one:
--
--     verify_spots.py    'tide_preference — string. One of: "low", "mid", "high", "all".
--                         ... default to "mid" if uncertain.'
--     classify_tides.py  'Use your knowledge of well-known spots where available; otherwise
--                         fall back to the general tide preference typical for that
--                         coastline and break style.'
--
-- Two spellings of one forced default, and the data shows it took. "mid" is 82% of
-- populated spots, and it carries the LOWEST mean self-scored confidence of the four values
-- (0.67, against low's 0.79) — the modal answer is also the least-believed one, which is the
-- signature of a default rather than a finding. Both instructions were removed in the commit
-- this migration accompanies; the prompts now require "unknown" when the model does not know
-- the specific break.
--
-- THE OLD SET COULD NOT SAY WHAT SURFERS SAY. {low, mid, high, all} has no way to express
-- "low to mid" or "mid to high", which are among the commonest real answers for a beach
-- break. A spot that works across two adjacent stages had to be filed under one of them or
-- under "all", and "all" is a stronger claim — genuinely tide-tolerant — so the pressure was
-- toward the single-stage guess. low_mid and mid_high exist to end that.
--
-- AND NOTHING REJECTED A BAD VALUE LOUDLY. An unexpected string passed through every layer:
-- verify_spots' validator silently coerced it to NULL with no log (the record survived, the
-- field did not); classify_tides dropped the whole record with a warning; the column is bare
-- TEXT with no constraint; and interpret.tide_multiplier ended in a bare `return 1.0`, so an
-- unrecognised preference rated as NEUTRAL — indistinguishable from a spot with no
-- preference at all — on every hour, forever, with no error anywhere. The test that should
-- have caught it asserted 1.0 for an unknown string as CORRECT and swept only a hard-coded
-- tuple of seven preferences, so a new value was never exercised. That is why the code
-- change landed first and this constraint exists: the database is now the layer that says no.
--
-- "unknown" IS ALSO A VALID invalid_reason, AND THEY ARE NOT THE SAME DOMAIN.
-- verify_spots._VALID_INVALID_REASONS is {surf_shop, river, lake, duplicate, non_surfable,
-- unknown} and _VALID_TIDE_PREFS now contains "unknown" too. One correction to the obvious
-- reading: these are not two columns. invalid_reason appears in NO migration and is absent
-- from db_import's upsert list — it lives only in verify_spots' in-memory record and in
-- spots_enriched.json, and never reaches this database. So the collision is real but it is a
-- Python-validator hazard, not a schema one, and it needs no constraint here. If
-- invalid_reason is ever promoted to a column it must get its OWN CHECK; the two sets share
-- the string and nothing else.
--
-- WHY THE CHECK REJECTS NOTHING TODAY — verified, not assumed. Every distinct value now
-- stored is NULL or a member of the new set, so this constraint can be added without
-- touching a row:
--
--     stored value   live rows   in new set?
--     'mid'                365   yes
--     NULL                 202   allowed by the IS NULL branch
--     'low'                 62   yes
--     'high'                 9   yes
--     'all'                  8   yes
--                          ---
--                          646
--
-- The distinct values are the only thing that matters to a CHECK, and there are five of
-- them, all admitted. Independently re-derived from the committed roster
-- (pipeline/spots_enriched.json), which gives the same five classes with no empty strings
-- and no unexpected value: mid 367, NULL 202, low 62, high 9, all 8 = 648. The roster carries
-- TWO MORE ROWS THAN THE DATABASE, both 'mid' (367 vs 365). That gap is not explained here
-- and is not load-bearing for this migration — it changes no distinct value and therefore
-- cannot change whether the constraint applies cleanly — but it means the roster and the
-- spots table disagree about two rows and something should find out why.
--
-- THE BACKFILL CANNOT ATTRIBUTE WHAT IT SETS. Three writers have set tide_preference —
-- classify_tides (LLM, writes tide_preference_confidence alongside), verify_spots (LLM, no
-- confidence), scrape_surf_forecast (regex over surf-forecast.com prose, no confidence) —
-- and NONE of them recorded which one won. They ran in whatever order the operator chose and
-- each overwrote the last. The scraper's own cache, pipeline/data/surf_forecast_scrape.json,
-- is absent from the repository and has no git history, so even the one artifact that could
-- have said what it extracted is gone. 'unattributed' is therefore the honest label for all
-- 446 existing values: it means "a value we hold and cannot source", which is a different
-- and weaker thing than 'unknown', and it must not be read as a provenance claim. Only
-- values written AFTER this migration can carry a real source.
--
-- NO DEFAULT ON THE NEW COLUMN, DELIBERATELY. A new spot arrives with
-- tide_preference_source NULL, which correctly reads as "nothing has set this yet" and is
-- distinguishable from 'unattributed' ("something set the preference and we cannot say
-- what"). db_import does not yet write the column — registering it there is part of the
-- provenance change that follows, not this one — so until then every new row is NULL by
-- construction rather than by accident.
--
-- CONSTRAINT IDEMPOTENCY FOLLOWS 015, NOT A pg_constraint LOOKUP. ALTER TABLE ADD CONSTRAINT
-- has no IF NOT EXISTS, and 015_surf_report_revisions.sql:46-49 already solved this with
-- DROP CONSTRAINT IF EXISTS followed by ADD CONSTRAINT. That pattern is used here for both
-- constraints because it is the one already in the tree AND because it is the better shape
-- for a value-list check: a pg_constraint existence guard would skip the ADD on re-run and
-- silently leave a STALE constraint in place the next time this set widens, which — given
-- that this migration exists precisely because the set widened once — is the failure mode to
-- design against.
--
-- Run in the Supabase SQL editor (idempotent).

ALTER TABLE spots ADD COLUMN IF NOT EXISTS tide_preference_source TEXT;

-- The widened value set. IS NULL OR ... IN (...) per 014_surf_reports.sql:44-47: NULL is the
-- state of 202 spots nothing has ever classified, and it must stay distinguishable from
-- 'unknown', which is a spot something looked at and declined to guess about. Both rate as
-- neutral in interpret.tide_multiplier; only one of them is an answer.
ALTER TABLE spots
  DROP CONSTRAINT IF EXISTS spots_tide_preference_check;
ALTER TABLE spots
  ADD CONSTRAINT spots_tide_preference_check CHECK (
    tide_preference IS NULL OR tide_preference IN (
      'low', 'low_mid', 'mid', 'mid_high', 'high', 'all', 'unknown'
    )
  );

-- Provenance, constrained the same way and for the same reason: an unconstrained TEXT column
-- is how tide_preference came to hold values nothing would reject.
--
--   researched              a source was consulted for THIS break and named it
--   scraped                 extracted from a surf-forecast.com page by scrape_surf_forecast
--   derived_from_break_type inferred from the break's type, not from the break
--   unattributed            held, but no writer recorded itself — see the backfill above
--   unknown                 the SOURCE is unknown, distinct from tide_preference='unknown',
--                           which is a claim about the tide rather than about provenance
ALTER TABLE spots
  DROP CONSTRAINT IF EXISTS spots_tide_preference_source_check;
ALTER TABLE spots
  ADD CONSTRAINT spots_tide_preference_source_check CHECK (
    tide_preference_source IS NULL OR tide_preference_source IN (
      'researched', 'scraped', 'derived_from_break_type', 'unattributed', 'unknown'
    )
  );

-- Idempotent by the IS NULL predicate: a re-run finds nothing left to set, and a row whose
-- source has since been corrected to something real is not reverted to 'unattributed'.
UPDATE spots
   SET tide_preference_source = 'unattributed'
 WHERE tide_preference IS NOT NULL
   AND tide_preference_source IS NULL;

COMMENT ON COLUMN spots.tide_preference_source IS
  'Where this row''s tide_preference came from. One of researched / scraped / '
  'derived_from_break_type / unattributed / unknown, or NULL when nothing has set a '
  'preference yet. NULL and ''unattributed'' are different states: NULL means no preference '
  'exists to source, ''unattributed'' means one does and no writer recorded itself — the '
  'state of all 446 values that predate this migration, because classify_tides, verify_spots '
  'and scrape_surf_forecast all wrote the field and none stamped provenance. '
  '''unknown'' describes the SOURCE; tide_preference=''unknown'' describes the TIDE. A row '
  'can legitimately be (tide_preference=''unknown'', tide_preference_source=''researched'') — '
  'someone looked it up and the answer was that nobody knows.';
