-- Which roster entries are missing from the spots table, and vice versa.
--
-- WHY THIS EXISTS. pipeline/spots_enriched.json holds 648 records; the spots table holds
-- 646. The gap is entirely in tide_preference = 'mid' (367 in the roster, 365 in the table),
-- so two roster spots have no row. This finds them by name rather than by guessing.
--
-- THE JOIN KEY IS slug, DERIVED FROM name — and it has to be derived, because the roster
-- carries NO identifier at all. Verified against all 648 records: no `slug`, no `id`, no
-- `spot_id`, no `osm_id`. The only fields that could identify a row are `name` and
-- (`lat`, `lng`).
--
-- slug is the right derivation because it is what the database itself keys on:
-- db_import.py:126 writes "slug": _slugify(spot.get("name") or "") and db_import.py:573
-- upserts with on_conflict="slug". So a roster entry and a table row correspond exactly when
-- their slugs match — by construction, not by convention.
--
-- The slugs below were produced by the same rule as db_import._slugify (pipeline/db_import.py
-- :52-57): lowercase, replace every run of non-[a-z0-9] with a single hyphen, strip leading
-- and trailing hyphens. All 648 slugs are distinct and none is empty, so the key is sound.
--
-- NOT id. spots.id is `SERIAL PRIMARY KEY` (001_initial_schema.sql:12), and db_import treats
-- it as database-managed — _DB_MANAGED_COLUMNS at db_import.py:191 is {id, geom, created_at,
-- updated_at} and the importer never writes it. Large non-sequential values like 203293 are
-- therefore a serial inflated by churn, not an external manifest id: Postgres consumes a
-- sequence value on every INSERT attempt including ones that hit ON CONFLICT, so repeated
-- full-roster upserts burn ~648 numbers each and the counter runs far ahead of the row count.
-- Nothing outside the database knows those ids, and the roster cannot be joined on them.
--
-- Names are inlined with '' escaping; 10 of the 648 contain an apostrophe.
--
-- Paste whole into the Supabase SQL editor. Read-only — SELECT only, no writes.

WITH roster(slug, name, tide_preference) AS (
  VALUES
    ('15th-street-del-mar'::text, '15th Street Del Mar'::text, 'mid'::text),
    ('38th-avenue', '38th Avenue', 'low'),
    ('56th-street', '56th Street', 'mid'),
    ('andrew-molera-state-park', 'Andrew Molera State Park', 'mid'),
    ('asilomar-state-beach', 'Asilomar State Beach', 'mid'),
    ('bird-rock', 'Bird Rock', 'low'),
    ('blackies', 'Blackies', 'mid'),
    ('bolinas', 'Bolinas', 'mid'),
    ('bolsa-chica-state-beach', 'Bolsa Chica State Beach', 'mid'),
    ('bombora', 'Bombora', 'low'),
    ('brooks-street', 'Brooks Street', 'mid'),
    ('c-street-ventura', 'C Street Ventura', 'mid'),
    ('campus-point-ucsb', 'Campus Point UCSB', 'low'),
    ('cardiff-reef', 'Cardiff Reef', 'low'),
    ('carlsbad-state-beach', 'Carlsbad State Beach', 'mid'),
    ('carmel-beach', 'Carmel Beach', 'mid'),
    ('carpinteria-state-beach', 'Carpinteria State Beach', 'mid'),
    ('cayucos-pier', 'Cayucos Pier', 'mid'),
    ('church', 'Church', 'mid'),
    ('coronado-shores', 'Coronado Shores', 'mid'),
    ('cottons', 'Cottons', 'low'),
    ('county-line', 'County Line', 'mid'),
    ('cowell-s-beach-children-s-surfing-area', 'Cowell''s Beach Children''s Surfing Area', 'high'),
    ('crescent-city-beach', 'Crescent City Beach', 'mid'),
    ('d-street-encinitas', 'D Street Encinitas', 'mid'),
    ('dana-point-california', 'Dana Point, California', 'mid'),
    ('davenport-landing', 'Davenport Landing', 'low'),
    ('del-mar-beach', 'Del Mar Beach', 'mid'),
    ('devereux', 'Devereux', 'low'),
    ('dillon-beach', 'Dillon Beach', 'mid'),
    ('doheny-state-beach', 'Doheny State Beach', 'high'),
    ('doran-beach', 'Doran Beach', 'mid'),
    ('el-capitan-state-beach', 'El Capitan State Beach', 'mid'),
    ('el-porto', 'El Porto', 'mid'),
    ('emma-wood-state-beach', 'Emma Wood State Beach', 'mid'),
    ('first-peak', 'First Peak', 'mid'),
    ('fort-point', 'Fort Point', 'high'),
    ('garbage-beach', 'Garbage Beach', 'mid'),
    ('half-moon-bay-jetty', 'Half Moon Bay Jetty', 'mid'),
    ('hammonds', 'Hammonds', 'mid'),
    ('hermosa-beach-pier', 'Hermosa Beach Pier', 'mid'),
    ('hermosa-beach-california', 'Hermosa Beach, California', 'mid'),
    ('humboldt-bay-jetty', 'Humboldt Bay Jetty', 'mid'),
    ('huntington-beach-pier', 'Huntington Beach Pier', 'mid'),
    ('huntington-beach-california', 'Huntington Beach, California', 'mid'),
    ('huntington-cliffs', 'Huntington Cliffs', 'low'),
    ('imperial-beach-pier', 'Imperial Beach Pier', 'mid'),
    ('imperial-beach-california', 'Imperial Beach, California', 'mid'),
    ('jalama-beach', 'Jalama Beach', 'mid'),
    ('jenner-beach', 'Jenner Beach', 'mid'),
    ('la-jolla-shores', 'La Jolla Shores', 'mid'),
    ('leadbetter-beach', 'Leadbetter Beach', 'mid'),
    ('leo-carrillo-state-beach', 'Leo Carrillo State Beach', 'mid'),
    ('leucadia', 'Leucadia', 'mid'),
    ('wind-and-sea', 'Wind and Sea', 'mid'),
    ('lovers-point', 'Lovers Point', 'mid'),
    ('lower-trestles', 'Lower Trestles', 'low'),
    ('lunada-bay', 'Lunada Bay', 'mid'),
    ('malibu-surfrider-beach', 'Malibu Surfrider Beach', 'mid'),
    ('manhattan-beach-pier', 'Manhattan Beach Pier', 'mid'),
    ('manresa-state-beach', 'Manresa State Beach', 'mid'),
    ('marina-state-beach', 'Marina State Beach', 'mid'),
    ('mavericks-california', 'Mavericks, California', 'mid'),
    ('mission-beach', 'Mission Beach', 'mid'),
    ('mondos', 'Mondos', 'mid'),
    ('montara-state-beach', 'Montara State Beach', 'mid'),
    ('moonlight-beach', 'Moonlight Beach', 'mid'),
    ('moonstone-beach-humboldt', 'Moonstone Beach Humboldt', 'mid'),
    ('morro-rock', 'Morro Rock', 'mid'),
    ('moss-landing', 'Moss Landing', 'mid'),
    ('natural-bridges', 'Natural Bridges', 'mid'),
    ('new-brighton-reef', 'New Brighton Reef', 'low'),
    ('newport-beach-california', 'Newport Beach, California', 'mid'),
    ('newport-point', 'Newport Point', 'low'),
    ('ocean-beach-pier-sd', 'Ocean Beach Pier SD', 'mid'),
    ('ocean-beach-sf', 'Ocean Beach SF', 'mid'),
    ('oceanside-harbor', 'Oceanside Harbor', 'mid'),
    ('oceanside-pier', 'Oceanside Pier', 'mid'),
    ('pacific-beach', 'Pacific Beach', 'mid'),
    ('pacifica-linda-mar', 'Pacifica Linda Mar', 'mid'),
    ('palos-verdes-cove', 'Palos Verdes Cove', 'low'),
    ('pismo-beach-pier', 'Pismo Beach Pier', 'mid'),
    ('pleasure-point', 'Pleasure Point', 'mid'),
    ('point-arena', 'Point Arena', 'mid'),
    ('ponto-beach', 'Ponto Beach', 'mid'),
    ('redondo-beach-california', 'Redondo Beach, California', 'mid'),
    ('redondo-breakwater', 'Redondo Breakwater', 'high'),
    ('refugio-state-beach', 'Refugio State Beach', 'mid'),
    ('rincon', 'Rincon', 'mid'),
    ('river-jetties', 'River Jetties', 'mid'),
    ('rockaway-beach-pacifica', 'Rockaway Beach Pacifica', 'mid'),
    ('rockpile', 'Rockpile', 'low'),
    ('salmon-creek-beach', 'Salmon Creek Beach', 'mid'),
    ('salt-creek', 'Salt Creek', 'mid'),
    ('san-diego-blacks-beach', 'San Diego Blacks Beach', 'mid'),
    ('san-elijo-state-beach', 'San Elijo State Beach', 'mid'),
    ('san-onofre', 'San Onofre', 'mid'),
    ('san-simeon', 'San Simeon', 'mid'),
    ('sand-dollar-beach', 'Sand Dollar Beach', 'mid'),
    ('sandspit', 'Sandspit', 'low'),
    ('santa-monica-beach', 'Santa Monica Beach', 'mid'),
    ('scotts-creek', 'Scotts Creek', 'mid'),
    ('seal-beach-pier', 'Seal Beach Pier', 'mid'),
    ('seal-beach-california', 'Seal Beach, California', 'mid'),
    ('second-peak', 'Second Peak', 'mid'),
    ('sewer-peak', 'Sewer Peak', 'mid'),
    ('sharp-park', 'Sharp Park', 'mid'),
    ('shell-beach', 'Shell Beach', 'mid'),
    ('shelter-cove', 'Shelter Cove', 'mid'),
    ('solana-beach', 'Solana Beach', 'mid'),
    ('steamer-lane', 'Steamer Lane', 'all'),
    ('stinson-beach', 'Stinson Beach', 'mid'),
    ('stone-steps', 'Stone Steps', 'mid'),
    ('strands-beach', 'Strands Beach', 'low'),
    ('suicide-s', 'Suicide''s', 'mid'),
    ('sunset-cliffs', 'Sunset Cliffs', 'low'),
    ('surf-beach-vandenberg', 'Surf Beach Vandenberg', 'mid'),
    ('surfside-jetty', 'Surfside Jetty', 'mid'),
    ('surfside-california', 'Surfside, California', 'mid'),
    ('swamis', 'Swamis', 'low'),
    ('t-street-beach', 'T Street Beach', 'mid'),
    ('tamarack', 'Tamarack', 'mid'),
    ('thalia-street', 'Thalia Street', 'mid'),
    ('the-hook', 'The Hook', 'mid'),
    ('the-pier-beach', 'The Pier Beach', 'mid'),
    ('the-wedge', 'The Wedge', 'high'),
    ('toes-over', 'Toes Over', 'mid'),
    ('topanga-beach', 'Topanga Beach', 'mid'),
    ('torrance-beach', 'Torrance Beach', 'mid'),
    ('torrey-pines-state-beach', 'Torrey Pines State Beach', 'mid'),
    ('tourmaline', 'Tourmaline', 'mid'),
    ('3-mile', '3 Mile', 'mid'),
    ('trestles', 'Trestles', 'low'),
    ('trinidad-state-beach', 'Trinidad State Beach', 'mid'),
    ('upper-trestles', 'Upper Trestles', 'mid'),
    ('venice-beach-breakwater', 'Venice Beach Breakwater', 'mid'),
    ('ventura-point', 'Ventura Point', 'mid'),
    ('waddell-creek', 'Waddell Creek', 'mid'),
    ('windansea-beach', 'Windansea Beach', 'low'),
    ('zuma-beach', 'Zuma Beach', 'mid'),
    ('bethany-beach', 'Bethany Beach', 'mid'),
    ('dewey-beach', 'Dewey Beach', 'mid'),
    ('indian-river-inlet', 'Indian River Inlet', 'mid'),
    ('lewes-street-surf-beach', 'Lewes Street Surf Beach', 'mid'),
    ('rehoboth-beach', 'Rehoboth Beach', 'mid'),
    ('amelia-island', 'Amelia Island', 'mid'),
    ('atlantic-beach', 'Atlantic Beach', 'mid'),
    ('bathtub-beach', 'Bathtub Beach', 'high'),
    ('boca-raton-inlet', 'Boca Raton Inlet', 'mid'),
    ('boynton-beach-inlet', 'Boynton Beach Inlet', 'mid'),
    ('cocoa-beach-pier', 'Cocoa Beach Pier', 'mid'),
    ('dania-beach-pier', 'Dania Beach Pier', 'mid'),
    ('daytona-beach', 'Daytona Beach', 'mid'),
    ('deerfield-beach-pier', 'Deerfield Beach Pier', 'mid'),
    ('delray-beach', 'Delray Beach', 'mid'),
    ('destin-jetty', 'Destin Jetty', 'mid'),
    ('flagler-beach-pier', 'Flagler Beach Pier', 'mid'),
    ('fort-lauderdale-beach', 'Fort Lauderdale Beach', 'mid'),
    ('fort-pierce-inlet', 'Fort Pierce Inlet', 'low'),
    ('haulover-inlet', 'Haulover Inlet', 'mid'),
    ('indian-rocks-beach', 'Indian Rocks Beach', 'mid'),
    ('jacksonville-beach-pier', 'Jacksonville Beach Pier', 'mid'),
    ('jetty-park-cocoa-beach', 'Jetty Park Cocoa Beach', 'low'),
    ('juno-beach-pier', 'Juno Beach Pier', 'mid'),
    ('jupiter-inlet', 'Jupiter Inlet', 'low'),
    ('lake-worth-pier', 'Lake Worth Pier', 'mid'),
    ('lori-wilson-park', 'Lori Wilson Park', 'mid'),
    ('marineland', 'Marineland', 'mid'),
    ('matanzas-inlet', 'Matanzas Inlet', 'mid'),
    ('mayport-poles', 'Mayport Poles', 'low'),
    ('mexico-beach', 'Mexico Beach', 'mid'),
    ('monster-hole', 'Monster Hole', 'mid'),
    ('naples-pier', 'Naples Pier', 'mid'),
    ('navarre-beach', 'Navarre Beach', 'mid'),
    ('new-smyrna-beach-inlet', 'New Smyrna Beach Inlet', 'mid'),
    ('north-jetty', 'North Jetty', 'mid'),
    ('okaloosa-island-pier', 'Okaloosa Island Pier', 'mid'),
    ('palm-beach', 'Palm Beach', 'mid'),
    ('panama-city-beach-pier', 'Panama City Beach Pier', 'mid'),
    ('patrick-air-force-base-beach', 'Patrick Air Force Base Beach', 'mid'),
    ('pensacola-beach', 'Pensacola Beach', 'mid'),
    ('playalinda-beach', 'Playalinda Beach', 'mid'),
    ('pompano-beach-pier', 'Pompano Beach Pier', 'mid'),
    ('ponce-inlet', 'Ponce Inlet', 'low'),
    ('ponte-vedra-beach', 'Ponte Vedra Beach', 'mid'),
    ('satellite-beach', 'Satellite Beach', 'mid'),
    ('sebastian-inlet', 'Sebastian Inlet', 'low'),
    ('south-beach-miami', 'South Beach Miami', 'mid'),
    ('st-augustine-beach-pier', 'St. Augustine Beach Pier', 'mid'),
    ('st-pete-beach', 'St. Pete Beach', 'mid'),
    ('treasure-island-fl', 'Treasure Island FL', 'mid'),
    ('venice-beach-fl', 'Venice Beach FL', 'mid'),
    ('vilano-beach', 'Vilano Beach', 'mid'),
    ('ala-moana-bowls', 'Ala Moana Bowls', 'low'),
    ('anahola-bay', 'Anahola Bay', 'mid'),
    ('backdoor-pipeline', 'Backdoor Pipeline', 'low'),
    ('banyans', 'Banyans', 'low'),
    ('banzai-pipeline', 'Banzai Pipeline', 'low'),
    ('barbers-point', 'Barbers Point', 'low'),
    ('bellows-beach', 'Bellows Beach', 'mid'),
    ('big-beach-makena', 'Big Beach Makena', 'mid'),
    ('canoes-waikiki', 'Canoes Waikiki', 'all'),
    ('chuns-reef', 'Chuns Reef', 'mid'),
    ('diamond-head-cliffs', 'Diamond Head Cliffs', 'low'),
    ('ehukai-beach-park', 'Ehukai Beach Park', 'low'),
    ('electric-beach', 'Electric Beach', 'mid'),
    ('flemings-beach', 'Flemings Beach', 'all'),
    ('haleiwa-ali-i-beach', 'Haleiwa Ali''i Beach', 'mid'),
    ('hanalei-bay', 'Hanalei Bay', 'mid'),
    ('hapuna-beach', 'Hapuna Beach', 'mid'),
    ('honoli-i', 'Honoli‘i', 'mid'),
    ('honolua-bay', 'Honolua Bay', 'low'),
    ('ho-okipa', 'Hoʻokipa', 'all'),
    ('kaisers', 'Kaisers', 'all'),
    ('kanaha-beach', 'Kanaha Beach', 'mid'),
    ('keaau-beach', 'Keaau Beach', 'mid'),
    ('kiahuna-beach', 'Kiahuna Beach', 'mid'),
    ('kolekole-beach-park', 'Kolekole Beach Park', 'mid'),
    ('lahaina-breakwall', 'Lahaina Breakwall', 'low'),
    ('laniakea', 'Laniakea', 'all'),
    ('launiupoko', 'Launiupoko', 'low'),
    ('log-cabins', 'Log Cabins', 'low'),
    ('lymans', 'Lymans', 'mid'),
    ('makaha', 'Makaha', 'mid'),
    ('makapuu-beach-park', 'Makapuu Beach Park', 'mid'),
    ('off-the-wall', 'Off The Wall', 'low'),
    ('pakala', 'Pakala', 'mid'),
    ('peahi-jaws', 'Peahi Jaws', 'all'),
    ('pine-trees-hawaii', 'Pine Trees Hawaii', 'mid'),
    ('poipu-beach', 'Poipu Beach', 'mid'),
    ('polihale-beach', 'Polihale Beach', 'mid'),
    ('puaena-point', 'Puaena Point', 'mid'),
    ('publics-waikiki', 'Publics Waikiki', 'mid'),
    ('p-p-kea-hawaii', 'Pūpūkea, Hawaii', 'low'),
    ('queens-waikiki', 'Queens Waikiki', 'all'),
    ('richardson-beach', 'Richardson Beach', 'mid'),
    ('rocky-point', 'Rocky Point', 'low'),
    ('sandy-beach-oahu', 'Sandy Beach Oahu', 'low'),
    ('sunset-beach-hawaii', 'Sunset Beach Hawaii', 'mid'),
    ('thousand-peaks-maui', 'Thousand Peaks Maui', 'low'),
    ('tunnels-beach', 'Tunnels Beach', 'mid'),
    ('turtle-bay', 'Turtle Bay', 'mid'),
    ('velzyland', 'Velzyland', 'low'),
    ('waimea-bay', 'Waimea Bay', 'mid'),
    ('white-plains-beach', 'White Plains Beach', 'mid'),
    ('yokohama-bay', 'Yokohama Bay', 'mid'),
    ('fortunes-rocks', 'Fortunes Rocks', 'mid'),
    ('gooch-s-beach', 'Gooch''s Beach', 'mid'),
    ('higgins-beach', 'Higgins Beach', 'mid'),
    ('long-sands-beach', 'Long Sands Beach', 'mid'),
    ('old-orchard-beach', 'Old Orchard Beach', 'mid'),
    ('scarborough-beach', 'Scarborough Beach', 'mid'),
    ('short-sands-beach-york', 'Short Sands Beach York', 'mid'),
    ('assateague-island-md', 'Assateague Island MD', 'mid'),
    ('ocean-city-md-28th-street', 'Ocean City MD 28th Street', 'mid'),
    ('ocean-city-md-inlet', 'Ocean City MD Inlet', 'low'),
    ('cisco-beach', 'Cisco Beach', 'mid'),
    ('coast-guard-beach', 'Coast Guard Beach', 'mid'),
    ('good-harbor-beach', 'Good Harbor Beach', 'mid'),
    ('horseneck-beach', 'Horseneck Beach', 'mid'),
    ('marconi-beach', 'Marconi Beach', 'mid'),
    ('nahant-beach', 'Nahant Beach', 'mid'),
    ('nantasket-beach', 'Nantasket Beach', 'mid'),
    ('nantucket-surf', 'Nantucket Surf', 'mid'),
    ('nauset-beach', 'Nauset Beach', 'mid'),
    ('plum-island', 'Plum Island', 'mid'),
    ('hampton-beach', 'Hampton Beach', 'mid'),
    ('jenness-beach', 'Jenness Beach', 'mid'),
    ('north-beach-rye', 'North Beach Rye', 'mid'),
    ('the-wall-hampton', 'The Wall Hampton', 'mid'),
    ('asbury-park', 'Asbury Park', 'mid'),
    ('atlantic-city', 'Atlantic City', 'mid'),
    ('avalon-nj', 'Avalon NJ', 'mid'),
    ('avon-by-the-sea', 'Avon-by-the-Sea', 'mid'),
    ('barnegat-light', 'Barnegat Light', 'mid'),
    ('bay-head', 'Bay Head', 'mid'),
    ('belmar', 'Belmar', 'mid'),
    ('bradley-beach', 'Bradley Beach', 'mid'),
    ('brigantine', 'Brigantine', 'mid'),
    ('deal', 'Deal', 'mid'),
    ('harvey-cedars', 'Harvey Cedars', 'mid'),
    ('island-beach-state-park', 'Island Beach State Park', 'mid'),
    ('long-beach-island', 'Long Beach Island', 'mid'),
    ('long-branch', 'Long Branch', 'mid'),
    ('manasquan-inlet', 'Manasquan Inlet', 'low'),
    ('margate', 'Margate', 'mid'),
    ('ocean-city-nj', 'Ocean City NJ', 'mid'),
    ('pier-village', 'Pier Village', 'mid'),
    ('point-pleasant-beach', 'Point Pleasant Beach', 'mid'),
    ('sandy-hook', 'Sandy Hook', 'mid'),
    ('sea-bright', 'Sea Bright', 'mid'),
    ('sea-isle-city', 'Sea Isle City', 'mid'),
    ('seaside-heights', 'Seaside Heights', 'mid'),
    ('seaside-park', 'Seaside Park', 'mid'),
    ('ship-bottom', 'Ship Bottom', 'mid'),
    ('spring-lake', 'Spring Lake', 'mid'),
    ('stone-harbor', 'Stone Harbor', 'mid'),
    ('strathmere', 'Strathmere', 'mid'),
    ('surf-city-nj', 'Surf City NJ', 'mid'),
    ('wildwood', 'Wildwood', 'high'),
    ('cupsogue-beach', 'Cupsogue Beach', 'mid'),
    ('ditch-plains', 'Ditch Plains', 'mid'),
    ('fire-island', 'Fire Island', 'mid'),
    ('flying-point-beach', 'Flying Point Beach', 'mid'),
    ('georgica-beach', 'Georgica Beach', 'mid'),
    ('gilgo-beach', 'Gilgo Beach', 'mid'),
    ('jones-beach', 'Jones Beach', 'mid'),
    ('lido-beach', 'Lido Beach', 'mid'),
    ('long-beach-ny', 'Long Beach NY', 'mid'),
    ('main-beach-east-hampton', 'Main Beach East Hampton', 'mid'),
    ('mecox-beach', 'Mecox Beach', 'mid'),
    ('montauk-point', 'Montauk Point', 'low'),
    ('point-lookout', 'Point Lookout', 'mid'),
    ('ponquogue-beach', 'Ponquogue Beach', 'mid'),
    ('robert-moses-state-park', 'Robert Moses State Park', 'mid'),
    ('rockaway-67th-street', 'Rockaway 67th Street', 'mid'),
    ('rockaway-90th-street', 'Rockaway 90th Street', 'mid'),
    ('rockaway-beach', 'Rockaway Beach', 'mid'),
    ('shinnecock-inlet', 'Shinnecock Inlet', 'mid'),
    ('smith-point-beach', 'Smith Point Beach', 'mid'),
    ('turtle-cove-montauk', 'Turtle Cove Montauk', 'low'),
    ('atlantic-beach-nc', 'Atlantic Beach NC', 'mid'),
    ('avalon-pier', 'Avalon Pier', 'mid'),
    ('avon-pier', 'Avon Pier', 'mid'),
    ('cape-hatteras-lighthouse', 'Cape Hatteras Lighthouse', 'low'),
    ('carolina-beach', 'Carolina Beach', 'mid'),
    ('corolla-beach', 'Corolla Beach', 'mid'),
    ('duck-pier', 'Duck Pier', 'mid'),
    ('emerald-isle', 'Emerald Isle', 'mid'),
    ('frisco-pier', 'Frisco Pier', 'low'),
    ('holden-beach', 'Holden Beach', 'mid'),
    ('jennettes-pier', 'Jennettes Pier', 'mid'),
    ('kill-devil-hills', 'Kill Devil Hills', 'mid'),
    ('kitty-hawk-pier', 'Kitty Hawk Pier', 'mid'),
    ('kure-beach', 'Kure Beach', 'mid'),
    ('nags-head-pier', 'Nags Head Pier', 'mid'),
    ('ocean-isle-beach', 'Ocean Isle Beach', 'mid'),
    ('ocracoke-beach', 'Ocracoke Beach', 'mid'),
    ('oregon-inlet', 'Oregon Inlet', 'low'),
    ('rodanthe', 'Rodanthe', 'mid'),
    ('salvo', 'Salvo', 'mid'),
    ('sunset-beach-nc', 'Sunset Beach NC', 'mid'),
    ('surf-city-nc', 'Surf City NC', 'mid'),
    ('the-point-buxton', 'The Point Buxton', 'low'),
    ('topsail-beach', 'Topsail Beach', 'mid'),
    ('wrightsville-beach', 'Wrightsville Beach', 'mid'),
    ('agate-beach-newport', 'Agate Beach Newport', 'mid'),
    ('bandon-beach', 'Bandon Beach', 'mid'),
    ('bastendorff-beach', 'Bastendorff Beach', 'mid'),
    ('brookings-beach', 'Brookings Beach', 'mid'),
    ('cannon-beach', 'Cannon Beach', 'mid'),
    ('cape-kiwanda', 'Cape Kiwanda', 'mid'),
    ('florence-south-jetty', 'Florence South Jetty', 'mid'),
    ('gold-beach', 'Gold Beach', 'mid'),
    ('hubbard-creek', 'Hubbard Creek', 'mid'),
    ('indian-beach-ecola', 'Indian Beach Ecola', 'mid'),
    ('lincoln-city-beach', 'Lincoln City Beach', 'mid'),
    ('nelscott-reef', 'Nelscott Reef', 'low'),
    ('nye-beach', 'Nye Beach', 'mid'),
    ('otter-rock', 'Otter Rock', 'mid'),
    ('pacific-city-beach', 'Pacific City Beach', 'mid'),
    ('roads-end', 'Roads End', 'mid'),
    ('seaside-cove', 'Seaside Cove', 'mid'),
    ('short-sands-beach-oswald-west', 'Short Sands Beach Oswald West', 'mid'),
    ('south-beach-newport', 'South Beach Newport', 'mid'),
    ('whiskey-run-beach', 'Whiskey Run Beach', 'mid'),
    ('antonio-s', 'Antonio''s', 'mid'),
    ('aviones', 'Aviones', 'mid'),
    ('crash-boat-beach', 'Crash Boat Beach', 'mid'),
    ('dogmans-rincon', 'Dogmans Rincon', 'mid'),
    ('gas-chambers-aguadilla', 'Gas Chambers Aguadilla', 'low'),
    ('indicators', 'Indicators', 'mid'),
    ('jobos-beach-isabela', 'Jobos Beach Isabela', 'mid'),
    ('la-pared-luquillo', 'La Pared Luquillo', 'mid'),
    ('maria-s', 'Maria''s', 'low'),
    ('middles-isabela', 'Middles Isabela', 'mid'),
    ('pine-grove-beach', 'Pine Grove Beach', 'mid'),
    ('playa-guajataca', 'Playa Guajataca', 'mid'),
    ('playa-kikita', 'Playa Kikita', 'mid'),
    ('playa-manati', 'Playa Manati', 'mid'),
    ('pools', 'Pools', 'low'),
    ('rincon-domes', 'Rincon Domes', 'mid'),
    ('sandy-beach', 'Sandy Beach', 'mid'),
    ('shacks-beach', 'Shacks Beach', 'low'),
    ('steps-beach-rincon', 'Steps Beach Rincon', 'mid'),
    ('surfers-beach-aguadilla', 'Surfers Beach Aguadilla', 'mid'),
    ('table-tops-aguadilla', 'Table Tops Aguadilla', 'low'),
    ('tres-palmas', 'Tres Palmas', 'high'),
    ('wilderness', 'Wilderness', 'mid'),
    ('charlestown-town-beach', 'Charlestown Town Beach', 'mid'),
    ('conant-ave', 'Conant Ave', 'mid'),
    ('east-matunuck-state-beach', 'East Matunuck State Beach', 'mid'),
    ('marys', 'Marys', 'mid'),
    ('matunuck', 'Matunuck', 'low'),
    ('misquamicut-state-beach', 'Misquamicut State Beach', 'mid'),
    ('monahans', 'Monahans', 'mid'),
    ('moonstone-beach-ri', 'Moonstone Beach RI', 'low'),
    ('narragansett-beach', 'Narragansett Beach', 'mid'),
    ('pilgrim-ave', 'Pilgrim Ave', 'mid'),
    ('point-judith', 'Point Judith', 'mid'),
    ('ruggles', 'Ruggles', 'low'),
    ('second-beach-newport', 'Second Beach Newport', 'mid'),
    ('third-beach-newport', 'Third Beach Newport', 'high'),
    ('cherry-grove-pier', 'Cherry Grove Pier', 'mid'),
    ('edisto-beach', 'Edisto Beach', 'mid'),
    ('folly-beach-pier', 'Folly Beach Pier', 'mid'),
    ('folly-beach-washout', 'Folly Beach Washout', 'mid'),
    ('garden-city-pier', 'Garden City Pier', 'mid'),
    ('hilton-head-island', 'Hilton Head Island', 'mid'),
    ('hunting-island', 'Hunting Island', 'mid'),
    ('isle-of-palms', 'Isle of Palms', 'mid'),
    ('kiawah-island-beach', 'Kiawah Island Beach', 'mid'),
    ('myrtle-beach-state-park', 'Myrtle Beach State Park', 'mid'),
    ('pawleys-island', 'Pawleys Island', 'mid'),
    ('surfside-beach-sc', 'Surfside Beach SC', 'mid'),
    ('61st-street-galveston', '61st Street Galveston', 'mid'),
    ('bob-hall-pier', 'Bob Hall Pier', 'mid'),
    ('galveston-seawall', 'Galveston Seawall', 'mid'),
    ('horace-caldwell-pier', 'Horace Caldwell Pier', 'mid'),
    ('isla-blanca-park', 'Isla Blanca Park', 'mid'),
    ('jp-luby-surf-park', 'JP Luby Surf Park', 'mid'),
    ('matagorda-beach', 'Matagorda Beach', 'mid'),
    ('mustang-island', 'Mustang Island', 'mid'),
    ('port-a-beach', 'Port A Beach', 'mid'),
    ('port-aransas-jetty', 'Port Aransas Jetty', 'low'),
    ('south-padre-island', 'South Padre Island', 'mid'),
    ('surfside-beach-tx', 'Surfside Beach TX', 'mid'),
    ('croatan-beach', 'Croatan Beach', 'mid'),
    ('first-street-jetty-vb', 'First Street Jetty VB', 'low'),
    ('sandbridge-beach', 'Sandbridge Beach', 'mid'),
    ('virginia-beach-oceanfront', 'Virginia Beach Oceanfront', 'mid'),
    ('cape-disappointment', 'Cape Disappointment', 'mid'),
    ('hobuck-beach', 'Hobuck Beach', 'mid'),
    ('kalaloch-beach', 'Kalaloch Beach', 'mid'),
    ('la-push-first-beach', 'La Push First Beach', 'mid'),
    ('la-push-second-beach', 'La Push Second Beach', 'mid'),
    ('la-push-third-beach', 'La Push Third Beach', 'mid'),
    ('long-beach-wa', 'Long Beach WA', 'mid'),
    ('ocean-shores', 'Ocean Shores', 'mid'),
    ('pacific-beach-wa', 'Pacific Beach WA', 'mid'),
    ('rialto-beach', 'Rialto Beach', 'mid'),
    ('shi-shi-beach', 'Shi Shi Beach', 'mid'),
    ('tokeland', 'Tokeland', 'mid'),
    ('westport-jetty', 'Westport Jetty', 'mid'),
    ('westport-light-state-park', 'Westport Light State Park', 'mid'),
    ('fiji', 'Fiji', 'mid'),
    ('tijuana-slough', 'Tijuana Slough', NULL),
    ('avalanches', 'Avalanches', NULL),
    ('pb-point', 'PB Point', NULL),
    ('law-street', 'Law Street', NULL),
    ('scripps-pier', 'Scripps Pier', NULL),
    ('seaside-reef', 'Seaside Reef', NULL),
    ('pipes', 'Pipes', NULL),
    ('trails', 'Trails', NULL),
    ('san-clemente-beach', 'San Clemente Beach', NULL),
    ('middles', 'Middles', NULL),
    ('rockpile-laguna', 'Rockpile (Laguna)', NULL),
    ('crystal-cove', 'Crystal Cove', NULL),
    ('corona-del-mar', 'Corona Del Mar', NULL),
    ('newport-jetties', 'Newport Jetties', NULL),
    ('seal-beach-jetty', 'Seal Beach Jetty', NULL),
    ('cabrillo-beach', 'Cabrillo Beach', NULL),
    ('white-point', 'White Point', NULL),
    ('haggarty-s', 'Haggarty''s', NULL),
    ('rat-beach', 'Rat Beach', NULL),
    ('bruce-s-beach', 'Bruce''s Beach', NULL),
    ('shitpipe', 'Shitpipe', NULL),
    ('dockweiler-beach', 'Dockweiler Beach', NULL),
    ('venice-beach-pier', 'Venice Beach Pier', NULL),
    ('santa-monica-pier', 'Santa Monica Pier', NULL),
    ('will-rogers', 'Will Rogers', NULL),
    ('sunset-point', 'Sunset Point', NULL),
    ('chart-house', 'Chart House', NULL),
    ('malibu-point', 'Malibu Point', NULL),
    ('point-dume', 'Point Dume', NULL),
    ('port-hueneme', 'Port Hueneme', NULL),
    ('silver-strand', 'Silver Strand', NULL),
    ('oxnard-beach', 'Oxnard Beach', NULL),
    ('ventura-harbor', 'Ventura Harbor', NULL),
    ('pitas-point', 'Pitas Point', NULL),
    ('faria-beach', 'Faria Beach', NULL),
    ('mussel-shoals', 'Mussel Shoals', NULL),
    ('tarpits', 'Tarpits', NULL),
    ('miramar', 'Miramar', NULL),
    ('mesa-lane', 'Mesa Lane', NULL),
    ('avila-beach', 'Avila Beach', NULL),
    ('grover-beach', 'Grover Beach', NULL),
    ('shell-beach-north', 'Shell Beach (North)', NULL),
    ('cable-landing', 'Cable Landing', NULL),
    ('piedras-blancas', 'Piedras Blancas', NULL),
    ('mole-point', 'Mole Point', NULL),
    ('boneyard', 'Boneyard', NULL),
    ('monterey-beach', 'Monterey Beach', NULL),
    ('mitchell-s-cove', 'Mitchell''s Cove', NULL),
    ('4-mile', '4 Mile', NULL),
    ('pigeon-point', 'Pigeon Point', NULL),
    ('pescadero', 'Pescadero', NULL),
    ('half-moon-bay', 'Half Moon Bay', NULL),
    ('pedro-point', 'Pedro Point', NULL),
    ('south-ocean-beach', 'South Ocean Beach', NULL),
    ('north-ocean-beach', 'North Ocean Beach', NULL),
    ('cronkhite', 'Cronkhite', NULL),
    ('point-reyes-north', 'Point Reyes North', NULL),
    ('mendocino', 'Mendocino', NULL),
    ('caspar', 'Caspar', NULL),
    ('jug-handle', 'Jug Handle', NULL),
    ('mackerricher', 'Mackerricher', NULL),
    ('ten-mile-beach', 'Ten Mile Beach', NULL),
    ('westport', 'Westport', NULL),
    ('agate-beach', 'Agate Beach', NULL),
    ('st-andrews-park', 'St Andrews Park', NULL),
    ('cape-san-blas', 'Cape San Blas', NULL),
    ('redington-pier', 'Redington Pier', NULL),
    ('madeira-beach', 'Madeira Beach', NULL),
    ('spring-ave', 'Spring Ave', NULL),
    ('twin-piers', 'Twin Piers', NULL),
    ('whitney-beach', 'Whitney Beach', NULL),
    ('coolidge', 'Coolidge', NULL),
    ('siesta-key', 'Siesta Key', NULL),
    ('englewood', 'Englewood', NULL),
    ('gasparilla', 'Gasparilla', NULL),
    ('captiva', 'Captiva', NULL),
    ('key-west', 'Key West', NULL),
    ('sunny-isles', 'Sunny Isles', NULL),
    ('spoils', 'Spoils', NULL),
    ('commercial-pier', 'Commercial Pier', NULL),
    ('hillsboro-inlet', 'Hillsboro Inlet', NULL),
    ('hillsboro-beach', 'Hillsboro Beach', NULL),
    ('palmetto-pavilion', 'Palmetto Pavilion', NULL),
    ('ocean-reef-park', 'Ocean Reef Park', NULL),
    ('hobe-beach', 'Hobe Beach', NULL),
    ('jensen-beach', 'Jensen Beach', NULL),
    ('vero-pier', 'Vero Pier', NULL),
    ('spessard', 'Spessard', NULL),
    ('ocean-ave', 'Ocean Ave', NULL),
    ('indiatlantic', 'Indiatlantic', NULL),
    ('canova-beach-park', 'Canova Beach Park', NULL),
    ('pelican-beach', 'Pelican Beach', NULL),
    ('16th-street-south', '16th Street South', NULL),
    ('flagler-ave', 'Flagler Ave', NULL),
    ('wilbur-by-the-sea', 'Wilbur by the Sea', NULL),
    ('a-street', 'A Street', NULL),
    ('atlantic-blvd', 'Atlantic Blvd', NULL),
    ('fort-clinch', 'Fort Clinch', NULL),
    ('jekyll-island', 'Jekyll Island', NULL),
    ('st-simons-island', 'St Simons Island', NULL),
    ('sea-island', 'Sea Island', NULL),
    ('blackbeard-island', 'Blackbeard Island', NULL),
    ('st-catherines-island', 'St. Catherines Island', NULL),
    ('tybee-island', 'Tybee Island', NULL),
    ('fripp-island', 'Fripp Island', NULL),
    ('berts-bar', 'Berts Bar', NULL),
    ('windjammer', 'Windjammer', NULL),
    ('wild-dunes', 'Wild Dunes', NULL),
    ('dewees-island', 'Dewees Island', NULL),
    ('south-island', 'South Island', NULL),
    ('oak-island-pier', 'Oak Island Pier', NULL),
    ('fort-fisher', 'Fort Fisher', NULL),
    ('carolina-beach-pier', 'Carolina Beach Pier', NULL),
    ('wrightsville-beach-south', 'Wrightsville Beach South', NULL),
    ('jolly-roger-pier', 'Jolly Roger Pier', NULL),
    ('seaview-pier', 'Seaview Pier', NULL),
    ('hatteras-ferry-docks', 'Hatteras Ferry Docks', NULL),
    ('north-buxton', 'North Buxton', NULL),
    ('s-turns', 'S-Turns', NULL),
    ('north-pea-island', 'North Pea Island', NULL),
    ('outer-banks-fishing-pier', 'Outer Banks Fishing Pier', NULL),
    ('abalone-street', 'Abalone Street', NULL),
    ('bath-house', 'Bath House', NULL),
    ('black-pelican', 'Black Pelican', NULL),
    ('north-end-virginia-beach', 'North End Virginia Beach', NULL),
    ('fenwick-island', 'Fenwick Island', NULL),
    ('gordon-pond', 'Gordon Pond', NULL),
    ('the-cove', 'The Cove', NULL),
    ('broadway-beach', 'Broadway Beach', NULL),
    ('grant-street', 'Grant Street', NULL),
    ('queen-street', 'Queen Street', NULL),
    ('poverty-beach', 'Poverty Beach', NULL),
    ('the-rocks', 'The Rocks', NULL),
    ('diamond-beach', 'Diamond Beach', NULL),
    ('north-wildwood', 'North Wildwood', NULL),
    ('30th-street-pier', '30th Street Pier', NULL),
    ('avalon-jetty', 'Avalon Jetty', NULL),
    ('south-end', 'South End', NULL),
    ('32nd-street', '32nd Street', NULL),
    ('quincy-ave', 'Quincy Ave', NULL),
    ('margate-pier', 'Margate Pier', NULL),
    ('ventor-pier', 'Ventor Pier', NULL),
    ('caesars-pier', 'Caesars Pier', NULL),
    ('brigantine-jetty', 'Brigantine Jetty', NULL),
    ('seaside-road', 'Seaside Road', NULL),
    ('wooden-jetty', 'Wooden Jetty', NULL),
    ('holyoke', 'Holyoke', NULL),
    ('beach-haven', 'Beach Haven', NULL),
    ('long-beach-township', 'Long Beach Township', NULL),
    ('mantoloking', 'Mantoloking', NULL),
    ('sea-girt', 'Sea Girt', NULL),
    ('ocean-grove', 'Ocean Grove', NULL),
    ('monmouth', 'Monmouth', NULL),
    ('breezy-point', 'Breezy Point', NULL),
    ('west-end-long-beach', 'West End Long Beach', NULL),
    ('saltaire', 'Saltaire', NULL),
    ('ocean-bay-park', 'Ocean Bay Park', NULL),
    ('davis-park', 'Davis Park', NULL),
    ('hither-hills', 'Hither Hills', NULL),
    ('terrace', 'Terrace', NULL),
    ('poles', 'Poles', NULL),
    ('radars', 'Radars', NULL),
    ('black-rock-point', 'Black Rock Point', NULL),
    ('dunes-park', 'Dunes Park', NULL),
    ('weekapaug', 'Weekapaug', NULL),
    ('east-beach', 'East Beach', NULL),
    ('breachway', 'Breachway', NULL),
    ('deep-hole', 'Deep Hole', NULL),
    ('salty-brine', 'Salty Brine', NULL),
    ('the-k-s', 'The K''s', NULL),
    ('point-judith-south', 'Point Judith South', NULL),
    ('scarborough', 'Scarborough', NULL),
    ('narrow-river', 'Narrow River', NULL),
    ('baileys-beach', 'Baileys Beach', NULL),
    ('first-beach', 'First Beach', NULL),
    ('squibnocket', 'Squibnocket', NULL),
    ('lucy-vincent', 'Lucy Vincent', NULL),
    ('long-point', 'Long Point', NULL),
    ('south-beach-state-park', 'South Beach State Park', NULL),
    ('madaket', 'Madaket', NULL),
    ('miacomet', 'Miacomet', NULL),
    ('nobadeer', 'Nobadeer', NULL),
    ('keyes-beach', 'Keyes Beach', NULL),
    ('green-harbor', 'Green Harbor', NULL),
    ('scituate', 'Scituate', NULL),
    ('winthrop-jetty', 'Winthrop Jetty', NULL),
    ('revere-beach', 'Revere Beach', NULL),
    ('lynn-beach', 'Lynn Beach', NULL),
    ('devereaux', 'Devereaux', NULL),
    ('salisbury', 'Salisbury', NULL),
    ('costellos', 'Costellos', NULL),
    ('fox-hill', 'Fox Hill', NULL),
    ('straws-point', 'Straws Point', NULL),
    ('pirates-cove', 'Pirates Cove', NULL),
    ('harbor-beach', 'Harbor Beach', NULL),
    ('ogunquit', 'Ogunquit', NULL),
    ('moody-point', 'Moody Point', NULL),
    ('crescent-beach', 'Crescent Beach', NULL),
    ('wells-beach', 'Wells Beach', NULL),
    ('drakes-island', 'Drakes Island', NULL),
    ('pine-point-beach', 'Pine Point Beach', NULL),
    ('reid-state-park', 'Reid State Park', NULL)
)
SELECT
    'roster entry with NO spots row'      AS direction,
    r.slug                                AS slug,
    r.name                                AS name,
    r.tide_preference                     AS tide_preference,
    NULL::timestamptz                     AS created_at,
    NULL::timestamptz                     AS updated_at
  FROM roster r
  LEFT JOIN spots s ON s.slug = r.slug
 WHERE s.slug IS NULL

UNION ALL

-- The reverse direction, so this answers whether the divergence is one-way or both.
-- created_at / updated_at are included here because the table has them and the roster does
-- not: the roster holds no timestamp of any kind (its only date-shaped field is
-- disambiguated_at, present on 2 records), so when a row appeared is knowable only from here.
SELECT
    'spots row with NO roster entry'      AS direction,
    s.slug                                AS slug,
    s.name                                AS name,
    s.tide_preference                     AS tide_preference,
    s.created_at                          AS created_at,
    s.updated_at                          AS updated_at
  FROM spots s
  LEFT JOIN roster r ON r.slug = s.slug
 WHERE r.slug IS NULL

 ORDER BY direction, slug;
